services:
  - type: web
    name: freqtrade-lacki
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
envVars:
    - key: FREQTRADE__EXCHANGE__KEY
      value: your_key
    - key: FREQTRADE__EXCHANGE__SECRET
      value: your_secret
    - key: FREQTRADE__API_SERVER__ENABLED
      value: "true"
    - key: FREQTRADE__API_SERVER__USERNAME
      value: "admin"
    - key: FREQTRADE__API_SERVER__PASSWORD
      value: "admin"
